core.entity_view_display.*.*.*.third_party.ds_chains:
  type: mapping
  label: 'Display suite chains settings'
  mapping:
    fields:
      type: sequence
      label: 'Chained fields'
      sequence:
        type: string
        label: 'Chained field'

ds.field_plugin.ds_chains:*:
  type: field.formatter.settings.[%parent.formatter]
  mapping:
    chain_settings:
      type: mapping
      mapping:
        ui_limit:
          type: integer
