# Schema for the configuration files of the Leaflet Mapbox module.

leaflet_mapbox.settings:
  type: config_object
  label: 'Leaflet Mapbox configuration'
  mapping:
    label:
      type: string
      label: 'Map label'
    api_version:
      type: string
      label: 'API version'
    code:
      type: string
      label: 'Map code'
    style_url:
      type: string
      label: 'Style URL'
    token:
      type: string
      label: 'Map access token'
    zoomlevel:
      type: integer
      label: 'Zoom Level'
    description:
      type: string
      label: 'Map description'
